name: hello program first

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven for dev environment
        run: mvn -Durl=${{DEV_URL}} -Dusername=${{DEV_USERNAME}} -Dpassword=${{DEV_PASSWORD}} -B package --file pom.xml
      - name: Build with Maven for test environment
        run: mvn -Durl=${{TEST_URL}} -Dusername=${{TEST_USERNAME}} -Dpassword=${{TEST_PASSWORD}} -B package --file pom.xml